[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = false

[font]
size = 14

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"

#[font.bold]
#family = "InconsolataGo Nerd Font"
#style = "Bold"
#
#[font.italic]
#family = "InconsolataGo Nerd Font"
#style = "Italic"
#
#[font.normal]
#family = "InconsolataGo Nerd Font"
#style = "Regular"

# New vertical split pane
[[keyboard.bindings]]
chars = "\u0006v"
key = "D"
mods = "Command"

# New horizontal split pane
[[keyboard.bindings]]
chars = "\u0006s"
key = "D"
mods = "Command|Shift"

# Close pane
[[keyboard.bindings]]
chars = "\u0006w"
key = "W"
mods = "Command"

# Switch to left pane
[[keyboard.bindings]]
chars = "\u0006h"
key = "H"
mods = "Command"

# Switch to down pane
[[keyboard.bindings]]
chars = "\u0006j"
key = "J"
mods = "Command"

# Switch to up pane
[[keyboard.bindings]]
chars = "\u0006k"
key = "K"
mods = "Command"

# Switch to right pane
[[keyboard.bindings]]
chars = "\u0006l"
key = "L"
mods = "Command"

# New tab
[[keyboard.bindings]]
chars = "\u0006c"
key = "T"
mods = "Command"

###############################################################################
# These next two are weird. It seems that Alacritty 0.13.0 applies the shift 
# modifier to the key you want to map. So Cmd+Shift+] is actually Cmd+Shift+}
# and Cmd+Shift+[ is actually Cmd+Shift+{.

# Next tab
[[keyboard.bindings]]
chars = "\u0006n"
key = "}"
mods = "Command|Shift"

# Previous tab
[[keyboard.bindings]]
chars = "\u0006p"
key = "{"
mods = "Command|Shift"

###############################################################################

# Resize pane left using Cmd + left arrow
[[keyboard.bindings]]
chars = "\u0006H"
key = "Left"
mods = "Command"

# Resize pane down using Cmd + down arrow
[[keyboard.bindings]]
chars = "\u0006J"
key = "Down"
mods = "Command"

# Resize pane up using Cmd + up arrow
[[keyboard.bindings]]
chars = "\u0006K"
key = "Up"
mods = "Command"

# Resize pane right using Cmd + right arrow
[[keyboard.bindings]]
chars = "\u0006L"
key = "Right"
mods = "Command"

###############################################################################
# Section: Switch to specific tabs
###############################################################################
[[keyboard.bindings]]
chars = "\u00061"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00062"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00063"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00064"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00065"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00066"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00067"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00068"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00069"
key = "Key9"
mods = "Command"

[scrolling]
history = 100000

[window]
decorations = "Full"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 1.0
title = ""
dynamic_title = false

# Import colors
[general]
import = [
    # uncomment the flavour you want below:
    #"~/.config/alacritty/catppuccin-latte.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin-macchiato.toml"
     "~/.config/alacritty/catppuccin-mocha.toml"
]

## Some of these key bindings are set specifically for tmux. See tmuxconf for
## more detail.
#key_bindings:
#  # cmd + d to open a vertical pane
#  - { key: D,        mods: Command,       chars: "\x06\x76" } 
#  # cmd + shift + d to open a horizontal pane
#  - { key: D,        mods: Command|Shift, chars: "\x06\x73" }
#  # cmd + w to close a window (tab)
#  - { key: W,        mods: Command,       chars: "\x06\x77" }
#  # cmd + h to switch to left pane
#  - { key: H,        mods: Command,       chars: "\x06\x68" }
#  # cmd + j to switch to down pane
#  - { key: J,        mods: Command,       chars: "\x06\x6a" }
#  # cmd + k to switch to up pane
#  - { key: K,        mods: Command,       chars: "\x06\x6b" }
#  # cmd + l to switch to right pane
#  - { key: L,        mods: Command,       chars: "\x06\x6c" }
#  # cmd + t to open new window (tab) 
#  - { key: T,        mods: Command,       chars: "\x06\x63" }
#  # cmd + shift + ] to go to next window (tab) 
#  - { key: RBracket, mods: Command|Shift, chars: "\x06\x6e" }
#  # cmd + shift + [ to go to previous window (tab) 
#  - { key: LBracket, mods: Command|Shift, chars: "\x06\x5b" }
#  # cmd + left to resize pane left 
#  - { key: Left,     mods: Command,       chars: "\x06\x48" }
#  # cmd + down to resize pane down 
#  - { key: Down,     mods: Command,       chars: "\x06\x4a" }
#  # cmd + up to resize pane up 
#  - { key: Up,       mods: Command,       chars: "\x06\x4b" }
#  # cmd + right to resize pane right 
#  - { key: Right,    mods: Command,       chars: "\x06\x4c" }
#  # cmd + <number> to switch to specific window
#  - { key: Key1,     mods: Command,       chars: "\x06\x31" }
#  - { key: Key2,     mods: Command,       chars: "\x06\x32" }
#  - { key: Key3,     mods: Command,       chars: "\x06\x33" }
#  - { key: Key4,     mods: Command,       chars: "\x06\x34" }
#  - { key: Key5,     mods: Command,       chars: "\x06\x35" }
#  - { key: Key6,     mods: Command,       chars: "\x06\x36" }
#  - { key: Key7,     mods: Command,       chars: "\x06\x37" }
#  - { key: Key8,     mods: Command,       chars: "\x06\x38" }
#  - { key: Key9,     mods: Command,       chars: "\x06\x39" }
