[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#24273a"
foreground = "#cad3f5"
dim_foreground = "#8087a2"
bright_foreground = "#cad3f5"

[colors.cursor]
text = "#24273a"
cursor = "#f4dbd6"

[colors.vi_mode_cursor]
text = "#24273a"
cursor = "#b7bdf8"

[colors.search.matches]
foreground = "#24273a"
background = "#a5adcb"

[colors.search.focused_match]
foreground = "#24273a"
background = "#a6da95"

[colors.footer_bar]
foreground = "#24273a"
background = "#a5adcb"

[colors.hints.start]
foreground = "#24273a"
background = "#eed49f"

[colors.hints.end]
foreground = "#24273a"
background = "#a5adcb"

[colors.selection]
text = "#24273a"
background = "#f4dbd6"

[colors.normal]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[colors.bright]
black = "#5b6078"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#a5adcb"

[colors.dim]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[[colors.indexed_colors]]
index = 16
color = "#f5a97f"

[[colors.indexed_colors]]
index = 17
color = "#f4dbd6"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.italic]
family = "Iosevka Term"
style = "Regular"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0006v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006s"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0006w"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0006["
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0006H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006L"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00061"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00062"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00063"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00064"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00065"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00066"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00067"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00068"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00069"
key = "Key9"
mods = "Command"

[scrolling]
history = 100000

[window]
decorations = "Buttonless"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.85
