ln -sF ~/src/jzbyers/dotfiles/zshrc ~/.zshrc
ln -sF ~/src/jzbyers/dotfiles/kitty ~/.config/kitty
ln -sF ~/src/jzbyers/dotfiles/alacritty ~/.config/alacritty
ln -sF ~/src/jzbyers/dotfiles/nvim ~/.config/nvim
ln -sF ~/src/jzbyers/dotfiles/bat ~/.config/bat
ln -sF ~/src/jzbyers/dotfiles/tmuxconf ~/.tmux.conf
ln -sF ~/src/jzbyers/dotfiles/psqlrc ~/.psqlrc
ln -sF ~/src/jzbyers/dotfiles/gitconfig ~/.gitconfig
ln -sF ~/src/jzbyers/dotfiles/ideavimrc ~/.ideavimrc
